# Generated by Django 5.2.1 on 2025-05-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('spot_type', models.CharField(choices=[('FRUIT_TREE', 'Fruit Tree'), ('HERB_GARDEN', 'Herb Garden'), ('COMMUNITY_PLOT', 'Community Plot'), ('WILD_EDIBLE', 'Wild Edible')], max_length=20)),
                ('description', models.TextField()),
                ('plant_species', models.CharField(max_length=100)),
                ('seasonality_notes', models.TextField()),
                ('access_notes', models.TextField(blank=True, default='Publicly Accessible', null=True)),
                ('safety_notes', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_INFO', 'Needs Info')], default='PENDING_REVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
